spring:
  jpa:
    hibernate:
      ddl-auto: create
    #    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/TrueClub
server:
  port: 8080